// Wild opponents with their base stat totals (sum of the 6 base stats) and types.
// Generated from PokeAPI /pokemon/{name} on 2026-09-26, not typed by hand.
export const OPPONENT_POOL = [
  { name: 'Bulbasaur', id: 1, bst: 318, types: ['grass', 'poison'] },
  { name: 'Venusaur', id: 3, bst: 525, types: ['grass', 'poison'] },
  { name: 'Charmander', id: 4, bst: 309, types: ['fire'] },
  { name: 'Charizard', id: 6, bst: 534, types: ['fire', 'flying'] },
  { name: 'Squirtle', id: 7, bst: 314, types: ['water'] },
  { name: 'Blastoise', id: 9, bst: 530, types: ['water'] },
  { name: 'Pikachu', id: 25, bst: 320, types: ['electric'] },
  { name: 'Vulpix', id: 37, bst: 299, types: ['fire'] },
  { name: 'Jigglypuff', id: 39, bst: 270, types: ['normal', 'fairy'] },
  { name: 'Meowth', id: 52, bst: 290, types: ['normal'] },
  { name: 'Psyduck', id: 54, bst: 320, types: ['water'] },
  { name: 'Growlithe', id: 58, bst: 350, types: ['fire'] },
  { name: 'Gengar', id: 94, bst: 500, types: ['ghost', 'poison'] },
  { name: 'Magikarp', id: 129, bst: 200, types: ['water'] },
  { name: 'Gyarados', id: 130, bst: 540, types: ['water', 'flying'] },
  { name: 'Lapras', id: 131, bst: 535, types: ['water', 'ice'] },
  { name: 'Ditto', id: 132, bst: 288, types: ['normal'] },
  { name: 'Eevee', id: 133, bst: 325, types: ['normal'] },
  { name: 'Snorlax', id: 143, bst: 540, types: ['normal'] },
  { name: 'Dragonite', id: 149, bst: 600, types: ['dragon', 'flying'] },
  { name: 'Mewtwo', id: 150, bst: 680, types: ['psychic'] },
  { name: 'Mew', id: 151, bst: 600, types: ['psychic'] },
  { name: 'Chikorita', id: 152, bst: 318, types: ['grass'] },
  { name: 'Cyndaquil', id: 155, bst: 309, types: ['fire'] },
  { name: 'Totodile', id: 158, bst: 314, types: ['water'] },
  { name: 'Pichu', id: 172, bst: 205, types: ['electric'] },
  { name: 'Togepi', id: 175, bst: 245, types: ['fairy'] },
  { name: 'Marill', id: 183, bst: 250, types: ['water', 'fairy'] },
  { name: 'Umbreon', id: 197, bst: 525, types: ['dark'] },
  { name: 'Piplup', id: 393, bst: 314, types: ['water'] },
  { name: 'Lucario', id: 448, bst: 525, types: ['fighting', 'steel'] },
  { name: 'Greninja', id: 658, bst: 530, types: ['water', 'dark'] },
  { name: 'Sylveon', id: 700, bst: 525, types: ['fairy'] },
  { name: 'Rowlet', id: 722, bst: 320, types: ['grass', 'flying'] },
  { name: 'Litten', id: 725, bst: 320, types: ['fire'] },
  { name: 'Popplio', id: 728, bst: 320, types: ['water'] },
  { name: 'Togedemaru', id: 777, bst: 435, types: ['electric', 'steel'] },
  { name: 'Sprigatito', id: 906, bst: 310, types: ['grass'] },
  { name: 'Fuecoco', id: 909, bst: 310, types: ['fire'] },
  { name: 'Quaxly', id: 912, bst: 310, types: ['water'] },
];
